# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  # 应用名称（nacos会将应用名称当作服务名称）
  application:
    name: nacos
  # 环境 dev|test|prod
  profiles:
    active: dev
  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    nacos:
      discovery:
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 39.99.189.192:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: 2a9937e4-a5e2-4347-bbb4-94849125394d
        # 注册到 nacos 的指定 group，默认为 DEFAULT_GROUP
        group: XINM